"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
command_timeout = 1000

format = """
$directory\
$git_branch\
$git_state\
$git_status\
$kubernetes\
$dotnet\
$cmd_duration\
$status\
$line_break\
$character"""

[character]
success_symbol = "[>](bold #e46876)"
error_symbol = "[>](bold #e46876)"

[memory_usage]
disabled = false
symbol = ""
threshold = 30
format = "[$symbol ${ram}]($style)"

[git_branch]
symbol = " "
format = "[$symbol$branch(:$remote_branch)]($style) "
style = "purple"

[git_status]
format = '([\( $all_status$ahead_behind\)]($style) )'
diverged = "<>⇡${ahead_count} ⇣${behind_count} "
conflicted = "=${count} "
behind = "⇣${count} "
ahead = "⇡${count} "
modified = "~${count} "
untracked = "?${count} "
stashed = "^${count} "
staged = "+${count} "
deleted = "x${count} "
renamed = "»${count} "
style = "grey"

[status]
disabled = false
format = "[$symbol $status]($style)"
symbol = ""
signal_symbol = ""
sigint_symbol = "𥉉"
not_found_symbol = ""
not_executable_symbol = ""

[cmd_duration]
disabled = false
min_time = 0
show_milliseconds = true
format = "[  $duration](grey) "

[directory]
truncate_to_repo = true
style = "bold cyan"
format = '[$path]($style)[$read_only]($read_only_style) '

[kubernetes]
symbol = "⎈"
format = '[[$symbol ($cluster)](fg:#769ff0)]($style)'
disabled = false
